version: '3'
services:
  meshblu_server:
    container_name: meshblu_server
    image: octoblu/meshblu
    command: ./test-start.sh
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - PRIVATE_KEY_BASE64=Ii0tLS0tQkVHSU4gUlNBIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUVvZ0lCQUFLQ0FRRUFnL283RUFQbDc2MW4rMWppc1Y2aE9MSU5iTXBFMHNjVVdwSjg5OW5RNnozS0FXV0pcbmM0RXVaOXJHZnNEVVJZUWNoUUNYZVoxV21WOWluV3liYXN0Y0liRGg0Y1l6K0oxUWRPQUNEWnFxL2ptY3hwZk1cbkVqR012VFFZM1JMd2lGTytlMmFkS29LUHRkQnpwUHl2dUg3SFJ3S0JqSEZId0cxeDlMalpXS21YRFUvOGNIQVhcbmNSRmRJdlBxYnZJWHQ4VjE5V3VHMnVEc2FvQytRNzdoc0RJd0xTQkVucENab1BIb0pITUJDZG9hdVJaTk9kSWFcblYzdTdFSDBUeExrek9CcVJYV09GV0crSFBLYURGZ2pjT1RidloyTHg5RkhRMjdZTHE5SFcxbGVpcENxbEpvR0hcbkM4T3pmZy9kRFVNTHRDZGNScmZYWXcyYVJHM1BsZGpoTHFQRXN3SURBUUFCQW9JQkFEa004SDhwMERuZGNmZWJcbkl0T2Rubi9OcURRQTgrTlJuNkRQZGlvR0JHUE1ZQWhlaGg1aUYxZFpvVGlsenAwR1VQWEZuYlU2cUhiQVh2YkNcblBpVGFKOGVBbVFScUU0bERKOForRnlVZVdSQndneTd0NjQ5cHovYnlFRlZ3bkgyeUJjTitSaTVjSmhkb05yVjVcbmJkU0pLVWV1ODZWc1NxSUtMWnFtVlg0WVFXM0ZLQU16SWoxeERJVHpmSHR0UG5VaFQ3WS9lK1lNa0xuVVg2UnhcbnJ5UkdtK0x4ZlRqdEFOSFZranlyL1VGMjQzSk9aZTFZQ1BTRzFKTmJDdnVMMHJCQ0pLRE41NXZ1YWI5MW9wZ2pcbkR5S1RNV1pxSzE5c2dieFV0SEF3cEMzVXlsbkM5eFdHTlphdFpROG9jTjRrL29VN1VxS2IyU1pIVFZGTmtpZkhcbk1BRVpROEVDZ1lFQXpFcERsb2V2S1JNeUducmxWQ2FGejVFWmhEZ1ZBRGJ0QkFpUFNmTWhoMjdYd0l3WitETlJcbmp0cGxTM0VpNHltSWRnbm1FWHlERFZsdUg5MnRyV0tPS1J3eFZJMU9UMTZGN0IyVUEzY2lWcW1KZmp6MFBDaWtcbjlOUkNFeUIxNENSaUF5UmlHWndEbkhXNko3K0pNSjBLM1JWWFpKWmFJZnZldVR6ZFBwSlBJQ01DZ1lFQXBXSXpcbmQzUlZRMzdpMnJkbWVsbjNYcHhzNGhLM2ViVU80VFRuRnJmQkF1QS9YcDhvVGtTaVNDd1dRaWNwM0xMTUdWWHRcbjVMUnhPMUFuNDlrL2pWREhYdGtxS1o2K00yTUZoQzFOM3RWNE1oTDFMVzltcmRUQUZKTXFLQWNneHhXcXU2R0hcbnpqQ1liRGpyTkpvL1F6a2t4bjJINHFIbW1lbEtKUkNOcnNvQnlqRUNnWUJ5YU5qblViL2dNaGJxUzQ5cGpGVitcblJKWFV2WS9OV2ZWdFA5bjNvVWxTenRuWHhONjZhUXN4Qk5DYjZwV09RUEZpb2ZLT01udzJtcklZK0k1T3Z4WThcbm9jUml4T3hwZU5kcHY3cm9JZTFDT1pwOTcyY2MxZXBrRHdlZUxKeTNWY2pxVjVMMUlySEhDd3VoUFJ4NDlFcGtcblBKS0FDOUFZbmpWQzZucEJrN0RxbndLQmdCcXNiZlNVTkxSQUlNSjUxZk5oMHozVktOS0Zoa1lBNTdkMjJ0YVZcbktISVlUT0FyOTBvNFU1d2tVQ3EzT2s4NEh5YnU3d0YyQU5VNkpsVGZVeHF0cnBvam1HTkNFUmNrbjEwa0dXMFpcbkxOdVdweWgrMFNhMEs0Nmw5YVNqRWF4S1dGRU95bUo4Ly9oa2JicjhMYnZmMllpUjhucWc5aHBZdi9hZVp0dU1cbkJTSGhBb0dBT3hYeUw1NXlmWU5sY1loRWhtdWUwWTJoZXpnZDcxeEJXNXM1UW5ibXY3VDRpMXJsM1VvWkNiM0RcbjZEM3QvTDk1VjBiWjJheE9BQkwvMEF6RDFqeDVaaFM4cG5jTzJJNVpZTEZob0RiOWlqYWRTSU9BNy9iQjYwdW1cbkxGNlNiT0cyM3BCTUxPRllyU0pOS3kyRzJuS2JZTlN4WGV6cW5xMXB4SWRSRWtRa3NiQT1cbi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tIgo=
      - PUBLIC_KEY_BASE64=Ii0tLS0tQkVHSU4gUFVCTElDIEtFWS0tLS0tXG5NSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQWcvbzdFQVBsNzYxbisxamlzVjZoXG5PTElOYk1wRTBzY1VXcEo4OTluUTZ6M0tBV1dKYzRFdVo5ckdmc0RVUllRY2hRQ1hlWjFXbVY5aW5XeWJhc3RjXG5JYkRoNGNZeitKMVFkT0FDRFpxcS9qbWN4cGZNRWpHTXZUUVkzUkx3aUZPK2UyYWRLb0tQdGRCenBQeXZ1SDdIXG5Sd0tCakhGSHdHMXg5TGpaV0ttWERVLzhjSEFYY1JGZEl2UHFidklYdDhWMTlXdUcydURzYW9DK1E3N2hzREl3XG5MU0JFbnBDWm9QSG9KSE1CQ2RvYXVSWk5PZElhVjN1N0VIMFR4TGt6T0JxUlhXT0ZXRytIUEthREZnamNPVGJ2XG5aMkx4OUZIUTI3WUxxOUhXMWxlaXBDcWxKb0dIQzhPemZnL2REVU1MdENkY1JyZlhZdzJhUkczUGxkamhMcVBFXG5zd0lEQVFBQlxuLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tIgo=
      - PEPPER=meshblu-test-pepper
      - MESHBLU_HTTP_PORT=3000
      - REDIS_URI=redis://redis:6379
      - CACHE_REDIS_URI=redis://redis:6379
      - FIREHOSE_REDIS_URI=redis://redis:6379
      - NAMESPACE=meshblu
      - JOB_TIMEOUT_SECONDS=30
      - CONNECTION_POOL_MAX_CONNECTIONS=100
      - DISABLE_LOGGING=true
      - JOB_LOG_REDIS_URL=redis://redis:6379
      - JOB_LOG_QUEUE=meshblu-core-log
      - JOB_LOG_SAMPLE_RATE=1.00
      - REQUEST_QUEUE_NAME=request:queue
      - RESPONSE_QUEUE_BASE_NAME=response:queue
      - CONCURRENCY=4
      - MONGODB_URI=mongodb://mongodb:27017/meshblu-test
    links:
      - "redis:redis"
      - "mongodb:mongodb"
  meshblu_stream:
    container_name: octoblu/meshblu-core-protocol-adapter-http-streaming
    image:  octoblu/meshblu-core-protocol-adapter-http-streaming:v2.1.1
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ALIAS_SERVER_URI=''
      - REDIS_URI=redis://redis:6379
      - CACHE_REDIS_URI=redis://redis:6379
      - FIREHOSE_REDIS_URI=redis://redis:6379
      - NAMESPACE=meshblu
      - JOB_TIMEOUT_SECONDS=30
      - CONNECTION_POOL_MAX_CONNECTIONS=100
      - DISABLE_LOGGING=true
      - JOB_LOG_REDIS_URL=redis://redis:6379
      - JOB_LOG_QUEUE=meshblu-core-log
      - JOB_LOG_SAMPLE_RATE=1.00
      - REQUEST_QUEUE_NAME=request:queue
      - RESPONSE_QUEUE_BASE_NAME=response:queue
    links:
      - "meshblu_server:meshblu_server"
      - "redis:redis"
  meshblu_mqtt:
    container_name: octoblu/meshblu-core-protocol-adapter-mqtt
    image: octoblu/meshblu-core-protocol-adapter-mqtt:v2.1.3
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ALIAS_SERVER_URI=http://meshblu_server:3000
      - REDIS_URI=redis://redis:6379
      - CACHE_REDIS_URI=redis://redis:6379
      - FIREHOSE_REDIS_URI=redis://redis:6379
      - NAMESPACE=meshblu
      - JOB_TIMEOUT_SECONDS=30
      - CONNECTION_POOL_MAX_CONNECTIONS=100
      - DISABLE_LOGGING=true
      - JOB_LOG_REDIS_URL=redis://redis:6379
      - JOB_LOG_QUEUE=meshblu-core-log
      - JOB_LOG_SAMPLE_RATE=1.00
      - REQUEST_QUEUE_NAME=request:queue
      - RESPONSE_QUEUE_BASE_NAME=response:queue
    links:
      - "meshblu_server:meshblu_server"
      - "redis:redis"

  meshblu_mqtt:
    container_name: meshblu_mqtt
    image: octoblu/meshblu-core-protocol-adapter-mqtt
    ports:
      - "1883:1883"
    environment:
      - PORT=1883
      - ALIAS_SERVER_URI=http://meshblu_server:3000
      - REDIS_URI=redis://redis:6379
      - CACHE_REDIS_URI=redis://redis:6379
      - FIREHOSE_REDIS_URI=redis://redis:6379
      - NAMESPACE=meshblu'
      - JOB_TIMEOUT_SECONDS=30
      - CONNECTION_POOL_MAX_CONNECTIONS=100
      - DISABLE_LOGGING=true
      - JOB_LOG_REDIS_URI=redis://redis:6379
      - JOB_LOG_QUEUE=meshblu-core-log
      - JOB_LOG_SAMPLE_RATE=0.00
      - REQUEST_QUEUE_NAME=v2:request:queue
      - RESPONSE_QUEUE_BASE_NAME=v2:response:queue
    links:
      - "redis:redis"
      - "meshblu_server:meshblu_server"
  # mqtt_1: 
  #   container_name: meshblu_mqtt
  #   image: meshblu
  #   ports:
  #     - "1883:1883"
  #   command:  pm2 start --no-daemon process.json
  #   environment:
  #     - REDIS_URI=redis://192.168.1.54:6379
  #     - ALIAS_SERVER_URI=http://192.168.1.54:3000
  #     - CACHE_REDIS_URI=redis://192.168.1.54:6379
  #     - FIREHOSE_REDIS_URI=redis://192.168.1.54:6379
  #     - JOB_LOG_REDIS_URI=redis://192.168.1.54:6379
  #     - JOB_LOG_QUEUE=redis://192.168.1.54:6379
    
  redis:
    container_name: redis:alpine
    image: redis
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27107"
      - "27018:27018"
  # haproxy:
  #   container_name: haproxy
  #   build: ./deployments/docker/haproxy/
  #   ports: 
  #     - "80:80"
  #     - "1883:1883"
  #     - "3000:3000"
  #     - "3001:3001"
  #   links:
  #     "meshblu_server:meshblu_server"
  #     "meshblu_mqtt:meshblu_mqtt"
  #     "meshblu_stream:meshblue_stream"
networks:
  default:
    driver: bridge
  