version: '3'
services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - ./deployments/docker/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:5.5.0
    volumes:
      - ./deployments/docker/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./deployments/docker/elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000/udp"
      - "5000:5000/tcp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.5.0
    volumes:
      - ./deployments/docker/elk/kibana/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch