user: vagrant

data_file: /home/cqshinn/devices.json
dest_file: /tmp
mode: file
user: ubuntu
group: ubuntu
protocol: http
host: ads-elb-external-1267527463.ap-southeast-1.elb.amazonaws.com
concurrency: 10
total: 10
pip_download_dest: /tmp
pip_version:
python: python
pip: pip
pip_proxy: ''
