---
- name: repository - allow for HTTPS repos on Debian systems
  apt:
    pkg: apt-transport-https
    update_cache: yes
    cache_valid_time: 3600
    state: present
  when: erlang_repo.split(':')[0] == "https" and ansible_distribution == "Debian"

- name: add erlang-solution public key for apt-secure
  apt_key:
    url: http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: add erlang-solutions repository
  apt_repository:
    repo: "deb {{ erlang_repo }}{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} {{ erlang_repo_components }}"
    update_cache: no
    state: present

- name: "update and upgrade ubuntu"
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - update
- name: update and install erlang packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - erlang-base
    - elixir
  tags:
    - install
- name: clone cli from git
  git:
    repo: https://github.com/enixdark/mesh-performance-tools.git
    dest: /opt/cli
- name: install rebar3 
  get_url: 
    url: https://github.com/erlang/rebar3/releases/download/{{ rebar3_version }}/rebar3
    dest: /usr/local/bin
    mode: 0755
  become: true
- name: install rebar
  command:  chdir=/opt/cli mix local.rebar --force
- name: install hex
  command:  chdir=/opt/cli mix local.hex --force
- name: install package of project
  command:  chdir=/opt/cli mix deps.get
- name: compile project
  command:  chdir=/opt/cli mix compile
