---

- hosts: server
  strategy: free
  gather_facts: no
  vars:
    - template_file: group_vars/all.yml
  become: yes
  tasks:
    - include: pip.yml

    - name: install docker
      shell: curl -sSL https://get.docker.com/ | sh

    - name: add user mod
      command: sudo usermod -aG docker {{ user }}

    - name: clone cli from git
      git:
        repo: https://github.com/enixdark/mesh-performance-tools.git
        dest: /opt/cli
    - name: go to dir that have cloned cli source code and buid docker image
      command: chdir=/opt/cli docker build . -t cli
    - name: copy file devices data to temp to use for docker 
      copy:
        src: "{{ data_file }}"
        dest: "{{ dest_file }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 755
    - name: install docker client 
      pip:
        name: docker-py
    - name: Start a container with a command
      docker_container:
        name: cli
        image: cli
        command: mix {{ protocol }} -h {{ host }} -m {{ mode }} /tmp/devices.json -c {{ concurrency }} -n {{ total }} --from {{ from }} --to {{ to }}
        volumes:
          - /tmp/devices.json:/tmp/devices.json
      become: true
      tags:
        - cli
    - name: Stop a container
      docker_container:
        name: cli
        state: stopped
      become: true
      tags:
        - stop
    