# set absolute path to avoid misunderstand path between ansinle version
- include: roles/mongo/tasks/ubuntu.yaml
  when: ansible_os_family == 'Debian'
# - stat: path=/etc/mongodb.conf
#   register: mongodb
# - name: copy mongodb config file to server
#   copy: src=./roles/mongodb/files/mongodb.conf dest=/etc/mongodb.conf mode=0644
#   when: not mongodb.stat.exists
#   notify: restart mongo server