---
- include: pip.yml
# - name: install docker
#   command: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

# - name: add deb repo
#   command: sudo touch /etc/apt/sources.list.d/docker.list

# - lineinfile: dest="/etc/apt/sources.list.d/docker.list" line="{{item}}"
#   with_items:
#     - "deb https://apt.dockerproject.org/repo ubuntu-trusty main"

# - name: apt update
#   apt: update_cache=yes

# - apt: name=docker-engine state=present

# - name: add user mod
#   command: sudo usermod -aG docker {{ user }}

# - name: clone cli from git
#   git:
#     repo: https://github.com/enixdark/mesh-performance-tools.git
#     dest: /opt/cli
- name: go to dir that have cloned cli source code and buid docker image
  command: chdir=/opt/cli docker build . -t cli
- name: copy file devices data to temp to use for docker 
  copy:
    src: "{{ data_file }}"
    dest: "{{ dest_file }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 755
- name: install docker client 
  pip:
    name: docker-py
- name: Start a container with a command
  docker_container:
    name: cli
    image: cli
    command: mix {{ protocol }} -h {{ host }} -m {{ mode }} ./samples/files/devices.json -c {{ concurrency }} -n {{ total }}
    volumes:
      - /tmp/devices.json:/.samples/files/devices.json
# - name: add user mod
#   command: sudo usermod -aG docker {{action_user}}